from config import err_file

with open(err_file, "a") as f:
    f.write(str(13)+'\n')

with open(err_file, "a") as f:
    f.write(str(25)+'\n')

with open(err_file, "a") as f:
    f.write(str(46)+'\n')